apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-shared

resources:
  - namespaces/platform-shared.yml
  - configmaps/secret-init-script.yml
  - jobs/secret-init-job.yml
