apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-shared

commonLabels:
  platform.jaccloud.nl/managed-by: argocd
  platform.jaccloud.nl/service: shared-init
  platform.jaccloud.nl/tenant: platform

resources:
  - namespaces/platform-shared.yml
  - configmaps/secret-init-script.yml
  - jobs/secret-init-job.yml
  - rbac/platform-operator-role.yml
  - rbac/platform-viewer-role.yml
  - rbac/platform-service-sa-role.yml
  - rbac/tenant-operator-role.yml
  - rbac/tenant-viewer-role.yml
  - rbac/tenant-workload-sa-role.yml
