apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-shared-test
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/jactools/platform-argocd-apps.git
    targetRevision: release/test
    path: apps/platform/shared/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-shared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true