apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ai-stor

resources:
  - ../../base

labels:
  - pairs:
      platform.jaccloud.nl/environment: dev
    includeSelectors: true

patches:
  - target:
      kind: PersistentVolumeClaim
      name: ai-stor-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: "5Gi"
