apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

labels:
  - includeSelectors: false
    pairs:
      platform.jaccloud.nl/managed-by: flux
      platform.jaccloud.nl/component: kyverno
      platform.jaccloud.nl/service: kyverno
      platform.jaccloud.nl/tenant: platform

resources:
  - policies/block-dockerhub-images.yml
  - policies/block-argocd-managed-writes.yml
