---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-dq-engine
  namespace: argocd
spec:
  project: dq
  source:
    repoURL: https://github.com/jactools/dq-made-easy.git
    targetRevision: release/test