---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-dq-shared
  namespace: argocd
spec:
  project: dq
  source:
    repoURL: file:///repos/dq-made-easy
    targetRevision: release/dev