---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-dq-shared
  namespace: argocd
spec:
  project: dq
  source:
    repoURL: "{{DQ_MADE_EASY_REPO_URL}}"
    targetRevision: feature/dq-prototype
    path: infra/k8s/overlays/shared-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dq-made-easy-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
