---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-dq-test
  namespace: argocd
spec:
  project: dq
  source:
    repoURL: https://github.com/jactools/dq-made-easy.git
    targetRevision: release/test
    path: k8s/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: dq-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true