---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-dq-ui
  namespace: argocd
spec:
  project: dq
  source:
    repoURL: file:///repos/dq-made-easy
    targetRevision: feature/dq-prototype
    path: infra/k8s/overlays/dev-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: dq-made-easy-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
