apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-keycloak

commonLabels:
  platform.jaccloud.nl/environment: dev

resources:
  - ../../base

# Dev ingress hostname and TLS
patches:
  - target:
      kind: Ingress
      name: keycloak
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: keycloak.dev.jac.dot
      - op: replace
        path: /spec/tls/0/hosts/0
        value: keycloak.dev.jac.dot
