apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-observability

commonLabels:
  platform.jaccloud.nl/environment: dev

resources:
  - ../../base

# Dev ingress hostnames
patches:
  - target:
      kind: Ingress
      name: grafana
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: grafana.dev.jac.dot
  - target:
      kind: Ingress
      name: loki
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: loki.dev.jac.dot
  - target:
      kind: Ingress
      name: prometheus
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: prometheus.dev.jac.dot
  - target:
      kind: Ingress
      name: tempo
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: tempo.dev.jac.dot
  - target:
      kind: Ingress
      name: otel-collector
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: otel-collector.dev.jac.dot
