apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maas-dev

commonLabels:
  platform.jaccloud.nl/environment: dev

resources:
  - ../../base

# Rename the base namespace 'maas' to 'maas-dev'
patches:
  - target:
      kind: Namespace
      name: maas
    patch: |
      - op: replace
        path: /metadata/name
        value: maas-dev
