apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Platform service: Observability stack
# Components: Loki, Prometheus, Tempo, Grafana, OTel Collector, Pushgateway

commonLabels:
  platform.jaccloud.nl/managed-by: argocd
  platform.jaccloud.nl/service: observability
  platform.jaccloud.nl/tenant: platform

resources:
  - namespace.yml
  - loki.yml
  - prometheus.yml
  - tempo.yml
  - grafana.yml
  - pushgateway.yml
  - otel-collector.yml
  - ingress.yml
