---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingestion-runner
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: "{{ARGOCD_REPO_URL}}"
    targetRevision: feature/prototype
    path: apps/platform/ingestion-runner/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
