apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ai-stor

resources:
  - ../../base

labels:
  - pairs:
      platform.jaccloud.nl/environment: prod
    includeSelectors: true

patches:
  - target:
      kind: PersistentVolumeClaim
      name: ai-stor-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: "50Gi"
  - target:
      kind: Deployment
      name: ai-stor
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
