apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ai-stor

resources:
  - namespace.yml
  - configmaps/ai-stor-init-script.yml
  - jobs/ai-stor-init-job.yml
  - ingress/kong-routes-reference.yml
  - deployment.yml
  - service.yml
  - headless-service.yml
  - configmap.yml
  - pvc.yml
  - license-secret.yml

labels:
  - pairs:
      platform.jaccloud.nl/managed-by: argocd
      platform.jaccloud.nl/service: ai-stor
      platform.jaccloud.nl/tenant: platform
    includeSelectors: true

commonAnnotations:
  platform.jaccloud.nl/workload-kind: service
  platform.jaccloud.nl/maas-register: "true"
  platform.jaccloud.nl/target-id: "LOCAL"
