apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ai-stor

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - headless-service.yml
  - configmap.yml
  - pvc.yml

commonLabels:
  platform.jaccloud.nl/managed-by: argocd
  platform.jaccloud.nl/service: ai-stor
