apiVersion: v1
kind: Secret
metadata:
  name: ai-stor-license
  labels:
    app.kubernetes.io/name: ai-stor
    app.kubernetes.io/part-of: platform-foundation
type: Opaque
stringData:
  minio.license: |
    eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhaWQiOjAsImNhcCI6MCwiaWF0IjoxLjc3ODcwMzMzMjAzMjgzNjkzOWU5LCJpc3MiOiJzdWJuZXRAbWluLmlvIiwibGlkIjoiMGZlYTc0YTEtNWMyZS00MjM2LTk5MjAtOTBhNDdjN2E2ZTU1Iiwib3JnIjoiIiwicGxhbiI6IkZSRUUiLCJzdWIiOiJwcm90b3R5cGVAamFjY2xvdWQubmwiLCJ0cmlhbCI6ZmFsc2V9.pVR4pgQbj6oz1sRrB1OcWF5yidDtS_3wvIqWgvxx1bUmwU4Wjxu35pHwM1fosMMOH_2OqmrWz629zWe5jkd6D5TIgVv_zwgqfcraJ2-iFfhNdNu-d1oq5CYY4uOV2zZ0
