apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-stor-data
  labels:
    app.kubernetes.io/name: ai-stor
    app.kubernetes.io/part-of: platform-foundation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
