apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: platform-secrets-store
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    platform.jaccloud.nl/managed-by: argocd
    platform.jaccloud.nl/service: eso
    platform.jaccloud.nl/tenant: platform
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: external-secrets
          namespace: platform-eso
      remoteNamespace: platform-redis
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: platform-eso
          key: ca.crt
