apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-shared

resources:
  - ../../base

labels:
  - pairs:
      platform.jaccloud.nl/environment: prod
    includeSelectors: true
