apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared/argocd/shared-dev.yml
  - shared/argocd/shared-test.yml
  - shared/argocd/shared-prod.yml
  - keycloak/argocd/keycloak-dev.yml
  - kong/argocd/kong-dev.yml
  - observability/argocd/observability-dev.yml
  - kafka/argocd/kafka-dev.yml
  - trino/argocd/trino-dev.yml
  - ai-stor/argocd/ai-stor-dev.yml
  - ai-stor/argocd/ai-stor-test.yml
  - ai-stor/argocd/ai-stor-prod.yml
  - redis/argocd/redis-dev.yml
  - airflow/argocd/airflow-dev.yml
  - docker-registry/argocd/docker-registry-dev.yml
  - pypi-server/argocd/pypi-dev.yml
  - kyverno/argocd/kyverno-controller-dev.yml
  - kyverno/argocd/kyverno-policies-dev.yml

patches:
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-shared-dev
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-shared-test
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-shared-prod
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-keycloak
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-kong
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-observability
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-kafka
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-trino
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-ai-stor-dev
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-ai-stor-test
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-ai-stor-prod
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-redis
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-airflow
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-docker-registry
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-pypi-server
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-kyverno
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-kyverno-policies
