apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak/argocd/keycloak-dev.yml
  - kong/argocd/kong-dev.yml
  - observability/argocd/observability-dev.yml
  - kafka/argocd/kafka-dev.yml
  - trino/argocd/trino-dev.yml
  - llm/argocd/llm-dev.yml
  - airflow/argocd/airflow-dev.yml


patches:
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-keycloak
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-kong
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-observability
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-kafka
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-trino
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-llm
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-airflow
