---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Tenant workloads (dq, maas, etc.)
  sourceRepos:
    - '*'
  destinations:
    - namespace: dq-dev
      server: '*'
    - namespace: dq-test
      server: '*'
    - namespace: maas-dev
      server: '*'
    - namespace: maas-test
      server: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
