apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dq-dev

commonLabels:
  platform.jaccloud.nl/environment: dev

resources:
  - ../../base

# Rename the base namespace 'dq' to 'dq-dev'
patches:
  - target:
      kind: Namespace
      name: dq
    patch: |
      - op: replace
        path: /metadata/name
        value: dq-dev
