apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-eso

labels:
  - includeSelectors: true
    pairs:
      platform.jaccloud.nl/environment: dev

resources:
  - ../../base
