apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base ArgoCD app manifests
resources:
  - ../../keycloak/argocd/keycloak-dev.yml
  - ../../kong/argocd/kong-dev.yml
  - ../../observability/argocd/observability-dev.yml

# Patch repo URLs
patches:
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-keycloak
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-kong
  - patch: |
      - op: replace
        path: /spec/source/repoURL
        value: file:///repos/platform-argocd-apps
    target:
      kind: Application
      name: platform-observability
