---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ai-stor-dev
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: file:///repos/platform-argocd-apps
    targetRevision: release/dev
    path: apps/platform/ai-stor/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-ai-stor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
