apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-registry

commonLabels:
  platform.jaccloud.nl/environment: dev

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: pypi-server
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: packages.dev.jac.dot
