---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kong
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: file:///repos/platform-argocd-apps
    targetRevision: release/dev