apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Platform service: PyPI server
# Shares namespace platform-registry with Docker Registry

commonLabels:
  platform.jaccloud.nl/managed-by: argocd
  platform.jaccloud.nl/service: pypi-server
  platform.jaccloud.nl/tenant: platform

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
