---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  # Kong configuration values shared across environments
  KONG_DATABASE: "postgres"
  KONG_PG_PORT: "5432"
  KONG_PROXY_LISTEN: "0.0.0.0:8000"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_LISTEN: "0.0.0.0:8444 ssl"
  KONG_DNS_VALID_TTL: "1"
  KONG_DNS_STALE_TTL: "0"
