---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-db-data
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi