apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-registry

labels:
- includeSelectors: true
  pairs:
    platform.jaccloud.nl/environment: dev
    platform.jaccloud.nl/managed-by: argocd
    platform.jaccloud.nl/service: docker-registry
    platform.jaccloud.nl/tenant: platform

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: docker-registry
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: docker-registry.dev.jac.dot
