# Kyverno controller (pre-rendered manifests from v1.13.2)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kyverno
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: "file:///repos/platform-argocd-apps"
    targetRevision: release/test
    path: apps/platform/kyverno/base/vendor
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true