---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-maas-orchestrator
  namespace: argocd
spec:
  project: maas
  source:
    repoURL: file:///repos/metadata-as-a-service
    targetRevision: release/dev