---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-maas-web
  namespace: argocd
spec:
  project: tenant
  source:
    repoURL: "{{MAAS_REPO_URL}}"
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: maas-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
