---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-maas-api-test
  namespace: argocd
spec:
  project: maas
  source:
    repoURL: https://github.com/jactools/metadata-as-a-service.git
    targetRevision: feature/prototype
    path: k8s/overlays/test-api
  destination:
    server: https://kubernetes.default.svc
    namespace: maas-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
