---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-maas-central-repo-test
  namespace: argocd
spec:
  project: maas
  source:
    repoURL: https://github.com/jactools/metadata-as-a-service.git
    targetRevision: release/test